.globl osTvType;        osTvType        = 0x80000300; nop; nop
.globl osRomType;       osRomType       = 0x80000304; nop; nop
.globl osRomBase;       osRomBase       = 0x80000308; nop; nop
.globl osResetType;     osResetType     = 0x8000030C; nop; nop
.globl osCicId;         osCicId         = 0x80000310; nop; nop
.globl osVersion;       osVersion       = 0x80000314; nop; nop
.globl osMemSize;       osMemSize       = 0x80000318; nop; nop
.globl osAppNMIBuffer;  osAppNMIBuffer  = 0x8000031C; nop; nop
